### ISSUE TITLE
Add Bootstrap to project boilerplate

### ISSUE THREAD

**Issue by tomrule007** [chingu-voyages/v12-geckos-team-01#2]
Sounds like we need to decide how we want to import bootstrap into our react project. This is new to me but this little [guide/article](https://www.techiediaries.com/react-bootstrap/) makes it sound like we got three options.

1. Importing Bootstrap from a CDN,
2. Installing Bootstrap from npm,
3. Using React Bootstrap package like Reactstrap

**ToDo**
- [ ] Discuss Pros/Cons
- [ ] Pick Option
- [ ] Implement Option

**Comment by tomrule007** [comment]
I'm leaning towards option 3 as it looks like the other two options require us also adding jQuery to the project which I think it would be nice to exclude any unnecessary packages to keep our project size to a minimum for efficiency and speed.

But then we would have to decide an a component package.

1. [reactstrap](https://reactstrap.github.io/)
2. [React Bootstrop] (https://react-bootstrap.github.io/)

I'm not sure of the pros/cons of these two options or if there are others as well that i have not included.

**Comment by tylerd81** [comment]
Yeah, adding the Bootstrap React library would be the best I think. It could become a mess if we use the bootstrap css and then have to add the class names all over our code.

**Comment by tomrule007** [comment]
We went with the 3rd option for adding bootstrap to the project, using React Bootstrap package, and went with react-bootstrap.

See pull request for details
